title:              GRAPHICVS ET VITA
email:              zlekdius@outlook.com
description:        Chang Liu's Site
author:             Chang
baseurl:            ""
url:                "https://hummawhite.github.io"

# Social Profiles
twitter_username:
github_username:    HummaWhite
facebook_username:
instagram_username:
linkedin_username:  chang-liu-0451a6208

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter:        rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
